name: sonar-scan
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}
          restore-keys: ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}
          restore-keys: sbt-
      - run: sbt 'clean; coverage; test; coverageReport; scapegoat' < /dev/null
      - uses: actions/upload-artifact@v2
        with:
          name: scoverage
          path: target/scala-2.13/scoverage-report/scoverage.xml
      - uses: actions/upload-artifact@v2
        with:
          name: scapegoat
          path: target/scala-2.13/scapegoat-report/scapegoat.xml
  sonar-scan:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}
          restore-keys: ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}
          restore-keys: sbt-
      - uses: actions/download-artifact@v2
        with:
          name: scapegoat
          path: target/scala-2.13/scapegoat-report
      - uses: actions/download-artifact@v2
        with:
          name: scoverage
          path: target/scala-2.13/scoverage-report
      - run: |
          sbt -Dsonar.host.url=${SONARQUBE_URL} \
              -Dsonar.login=${SONARQUBE_ACCESS_TOKEN} \
              sonarScan < /dev/null
        env:
          SONARQUBE_URL: ${{secrets.SONARQUBE_URL}}
          SONARQUBE_ACCESS_TOKEN: ${{secrets.SONARQUBE_ACCESS_TOKEN}}
